# Docs para el deploy en Azure Functions: https://github.com/azure/functions-action
# Más GitHub Actions para Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - visitas-application

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: visitas-application # Nombre de la Function App en Azure
  PACKAGE_DIRECTORY: '.' # Directorio que contiene el pom.xml
  JAVA_VERSION: '11' # Versión de Java usada en la función

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Necesario para autenticación OIDC en Azure
      contents: read # Requerido para actions/checkout

    steps:
      - name: 'Checkout del código'
        uses: actions/checkout@v4

      - name: 'Configurar Java SDK'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Construir el JAR con Maven'
        run: |
          mvn clean package -DskipTests

      - name: 'Verificar que el JAR se generó correctamente'
        run: |
          ls -l target/*.jar || (echo "No se encontró el archivo JAR" && exit 1)

      - name: 'Login en Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04ADA7C7D2464CB98CE188E3A0B088F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AD5A9A3CD034A15BEA224D93F9492F6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EA656072DC5742BFB523935152ACF33D }}

      - name: 'Desplegar en Azure Functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}/target/*.jar'
          respect-pom-xml: true

      - name: 'Reiniciar la Function App después del despliegue'
        run: |
          az functionapp restart --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group Proyecto-Codorniz